# Generated by Django 4.0.5 on 2022-06-26 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0002_rename_title_expense_expense_remove_expense_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categoty_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_category_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='time_stamp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='time_stamp',
            field=models.DateField(auto_now=True),
        ),
    ]
