# Generated by Django 4.0.5 on 2022-06-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_expensecategory_profile_incomecategory_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
