# Generated by Django 4.0.5 on 2022-06-26 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_expensecategory_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expense_category', to='finances.expensecategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='income_category', to='finances.incomecategory'),
            preserve_default=False,
        ),
    ]
