# Generated by Django 4.0.5 on 2022-07-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_expense_category_income_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='time_stamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='time_stamp',
            field=models.DateField(),
        ),
    ]
