# Generated by Django 4.0.5 on 2022-07-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_expense_time_stamp_alter_income_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='total_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
