# Generated by Django 4.0.5 on 2022-11-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_alter_expense_note_alter_income_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='note',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
